name: google_maps_markerclusterer
description: Creates and manages per-zoom-level clusters for large amounts of markers.
version: 0.1.1
homepage: https://github.com/reyerstudio/google-maps-markerclusterer
author: St√©phane Este-Gracias <sestegra@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  google_maps: ^3.2.2
  js_wrapping: ^0.4.1

dev_dependencies:
  build_runner: ^0.4.0+3
  browser: ^0.10.0
  html: ^0.12.0
  js_wrapping_generator: ^0.4.1
  source_gen: ^0.7.1
  test: ^0.12.0

#dependency_overrides:
#  js_wrapping:
#    path: ../dart-js-wrapping2/js_wrapping
#  js_wrapping_generator:
#    path: ../dart-js-wrapping/js_wrapping_generator
